### ISSUE TITLE
sigROISignal not emitted in silx 0.10.1?

### ISSUE THREAD

**Issue by alexbjorling** [silx-kit/silx#2527]
I have an application which relies on the ROI widget in an instance of a `PlotWindow` subclass emitting a `sigROISignal`. In silx 0.10.1 this signal isn't received any more. I've accessed the signal as follows (where `self.spectrum`is the `PlotWindow`subclass instance).

```
self.spectrum.getCurvesRoiDockWidget().sigROISignal.connect(self.updateMap)
```
and now also tried
```
self.spectrum.getCurvesRoiWidget().sigROISignal.connect(self.updateMap)
```
but no luck. The docs say that this signal is deprecated, but what signal am I supposed to look for instead? The docs refer to `CurvesRoiWidget.sigRoiSignal` but that doesn't seem to exist.

**Comment by alexbjorling** [comment]
OK I see that this is raised already in  #2468

**Comment by alexbjorling** [comment]
Or  #427

**Comment by vallsv** [comment]
Yes, it is fixed in 0.10.2. And already packaged in pypi.

**Comment by payno** [comment]
> but no luck. The docs say that this signal is deprecated, but what signal am I supposed to look for instead? The docs refer to `CurvesRoiWidget.sigRoiSignal` but that doesn't seem to exist.

There is a typo on the documentation. The one to be used is the one from `CurvesROIWidget`. So your second option.

> OK I see that this is raised already in #2468

Yes it was missing in some cases (when changing ROI) but it has been fixed for the 0.10.1 so the issue has been fixed and closed (so in 0.10.1).

I just try the simple code (which seems close to yours):
```python

def test():
    app = qt.QApplication([])
    plot = Plot1D()
    plot.addCurve(x=range(10), y=range(10))
    q_obj = TestObj()
    plot.getCurvesRoiWidget().sigROISignal.connect(q_obj.updateMap)

    plot.show()
    app.exec_()


class TestObj(qt.QObject):
    def updateMap(self, *arg, **kwargs):
        print('call back activated')

test()
```

This seems to work with my configuration. Can you tell us a little bit more about your use case ? When are you expecting signals ? Can you try the code bellow and confirm that you are receiving some signals ?

**Comment by alexbjorling** [comment]
Thanks. Yes, the example code works. In fact I get 3 signals when I open the ROI widget, 2 signals when I add or delete a ROI, and 3 signals every time I change the limits of a ROI. Is it supposed to work like that and do I have to filter it myself?

I built this on silx 0.3.0 or so and it almost hasn't broken until now so that's OK. Now I also had to change the way I access the ROIs, but the new API (maybe that changed a few releases back) is cleaner.

The application is here,
https://github.com/alexbjorling/nanomax-analysis-utils/tree/master/apps/scanViewer

**Comment by payno** [comment]
For information: current behavior on my computer:

when delete a new ROI: 2 signals
When add a new ROI: 2 signals
When the widget is open: 3 signals
When changing ROI limits: I only get one

With 0.9:

When the widget is open: no signals
When I change the active ROI: one signal.
When I had a new ROI: no signals, but I guess the active ROI is not changing (even if the line is selected)
When I delete a ROI: no signals (even if was the active ROI)

Of course we have to check on this and filter it on our side

**Comment by payno** [comment]
the PR #2537 should fix the problem.

@alexbjorling would you have time to test this PR and make sure it work with your program ?

**Comment by alexbjorling** [comment]
Thanks, but I still get 3 signals both with my program and with the toy example above. Did you run the code above?

**Comment by payno** [comment]
thanks for the feedback.
When do you have those three signals ? When the widget appears ?
Because now I only have one (with the example above).
Because we create the ICR roi on the fly.
This is a different behavior compare to 0.9 but it make sense from my point of view but can be discuss.

**Comment by payno** [comment]
did you reinstall from the 'fix_2527' pull request branch.
something like upstream/pr/2537 if upstream is the silx 'master' repository
so it might be origin/pr/2537 if you cloned directly from the original silx repository

**Comment by alexbjorling** [comment]
I got three signals when changing the limits of existing ROIs.

I did
~~~
git clone https://github.com/payno/silx.git
cd silx
git checkout fix_2527
pip install . --user
~~~

**Comment by alexbjorling** [comment]
Yes it does, both in the above example and in my application. Thanks for acting on this!
