### ISSUE TITLE
unfinished polygon ROI causes error

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#3028]
When drawing a polygon ROI in a plot widget, if I accidentaly right click before finishing the polygon, I end up with an unfinished shape. The ROI appears in the ROIManager table, and it appears like it can be deleted. However, when I leave the ROI drawing mode after deleting it, I get this error :

```
  File "C:\Users\Pierre\AppData\Local\Programs\Python\Python37\lib\site-packages
\silx\gui\plot\tools\roi.py", line 190, in _plotInteractiveModeChanged
    self.__roiInteractiveModeEnded()
  File "C:\Users\Pierre\AppData\Local\Programs\Python\Python37\lib\site-packages
\silx\gui\plot\tools\roi.py", line 420, in __roiInteractiveModeEnded
    self.removeRoi(self._drawnROI)
  File "C:\Users\Pierre\AppData\Local\Programs\Python\Python37\lib\site-packages
\silx\gui\plot\tools\roi.py", line 322, in removeRoi
    'RegionOfInterest does not belong to this instance')
ValueError: RegionOfInterest does not belong to this instance

```

And when I then call `RoiManager.getRois()`, the deleted ROI is present in the returned list.

I tried disabling the context menu in my plot widget with `self.getWidgetHandle().setContextMenuPolicy(qt.Qt.NoContextMenu)`, but the bug happens even without context menu.

**Comment by PiRK** [comment]
I also see  the same error message if I delete the polygon ROI in the RoiManager table before finishing the polygon (last point not clicked). After that, if I change drawing mode, or click on polygon mode again, each new ROI that I draw is added twice to the RoiManager table.

These errors can be reproduced with `examples/plotInteractiveImageROI`

**Comment by vallsv** [comment]
Hi PiRK, I was working around that, i will take a look.

I have tested this behavior without problem recently, i will try again.

**Comment by vallsv** [comment]
BTW, did you try with the master?

**Comment by vallsv** [comment]
With my branch, i am not able to make it fail. And if i remove the ROI, it is recreated automatically. But no exception.

**Comment by PiRK** [comment]
I will try the master, thank you.

**Comment by vallsv** [comment]
THat master have another pbm btw. If you have an exception with an `abort` function it will be fixed.

**Comment by vallsv** [comment]
If you still have rights you could take a look at #3029 and merge it. Else @t20100 is maybe around.

**Comment by t20100** [comment]
Can this be closed with PR #3029 being merged?

**Comment by PiRK** [comment]
Probably. I haven’t been able to test the master myself (I still need to restart the computer after installing compiling tools on Windows). 

The bug was noticed on silx 0.13.0b0. If the fixes  are posterior to that release, it’s probably fine.

**Comment by PiRK** [comment]
Is there a silx wheel  for python 3.7 generated automatically  somewhere?

**Comment by t20100** [comment]
Yes, there are weekly builds available here: https://silx.gitlab-pages.esrf.fr/bob/silx/
.. but it's currently broken due to #3030 and issues in gitlab config that I'm currently fixing.
So it should be fixed soon.

**Comment by PiRK** [comment]
The error message is fixed, and now I don’t see the weird behavior of followinq ROIs being added multiple times anymore.

When I change ROI drawing mode with an unfinished polygon, the polygon disappears, which is good.

The only remaining issue happens when I right click. The following left clicks keep adding points, but with a delay of 1 click. To be more clear: if I click at position (X0, Y0) just after an accidental right click, nothing happens. If I then click at position (X1, Y1), the point at (X0, Y0) is added, then the following click adds the point at position (X1, Y1)... etc

**Comment by t20100** [comment]
OK, this is better but not completely fixed.
I already had issues with right click because it is used for the context menu... maybe we can do something about it, but I don't have an idea right now.

**Comment by t20100** [comment]
Wheels on https://silx.gitlab-pages.esrf.fr/bob/silx/ should be available in a moment....

**Comment by PiRK** [comment]
I managed to install Visual Studio on my machine and reboot, but thanks. It will be useful for updating silx for my tester. :)

**Comment by vallsv** [comment]
I already did things to improve the behavior on a branch. I can take some time to improve it a little more. That's the kind of things we know it was sweep under the carpet for a long time.

**Comment by vallsv** [comment]
- The easiest thing is to cancel the polygon on a right mouse click.
- A better thing could be to make it works and to add an option on the menu to close the polygon.

That's only about ROIs. And for polygon draw interaction, we should do the same. That's the tricky part i think.

**Comment by vallsv** [comment]
> if I click at position (X0, Y0) just after an accidental right click, nothing happens. If I then click at position (X1, Y1), the point at (X0, Y0) is added, then the following click adds the point at position (X1, Y1)... etc

Here i tried, but i don't have this behavior. I only noticed that the plot is not updated while the mouse do not move and the menu was closed just closed, but i do not noticed any thing else.

**Comment by PiRK** [comment]
The difference in behavior on my side could be caused by PySide2?

I think the current behavior  (allowing to finish the ROI by clicking on the last point) is probably better than canceling the polygon. I never accidentaly right clicked myself, but my tester tells me it happens a few times when you spend 2 hours drawing ROIs. Cancelling the shape would be more frustrating, if he spent a minute or longer drawing it.

Anyway, most of the problems are solved, so we can push it under the carpet again for a little while. I can try to figure out what specifically causes the issue on my computer later. I plan to look closely at the ROI tool again in a few weeks, to try to change some interactions.

**Comment by vallsv** [comment]
I will try again with PySide then, thanks.

**Comment by vallsv** [comment]
I was not able to reproduce the behavior with PySide2. But i changed few other things. So if you can check that there is no regression on your side with the PR #3033 it could be useful to know.

**Comment by PiRK** [comment]
I will test it tomorrow.

**Comment by t20100** [comment]
closed by #3033
